<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDatx6ul\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDatx6ul/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerDatx6ul.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerDatx6ul\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerDatx6ul\appProdProjectContainer([
    'container.build_hash' => 'Datx6ul',
    'container.build_id' => '24f61d6b',
    'container.build_time' => 1665999090,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDatx6ul');
